# Generated by Django 3.2.9 on 2022-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_cozmo', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
